# ref: https://docs.travis-ci.com/user/languages/python/
language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

before_install:
  - python -m pip install --upgrade pip
  - pip install poetry

install:
  - poetry install

script:
  - poetry run python -m pytest