# ref: https://docs.travis-ci.com/user/languages/python/
language: python

dist: jammy

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install --user -r travis-requirements.txt --use-feature=2020-resolver

script:
  - python -m pytest