# ref: https://docs.travis-ci.com/user/languages/python/
language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - pip install poetry

script:
  - poetry install
  - poetry run pytest