# ref: https://docs.travis-ci.com/user/languages/python/
language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"

before_install:
  - python -m pip install --upgrade pip
  - curl -sSL https://install.python-poetry.org | python

install:
  - poetry install

script:
  - poetry run python -m pytest